-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgowUanqou8d5wb3Xh
zritC8aeScHxMaW8kuMg/qFo506gCgYIKoZIzj0DAQehRANCAAQthgeEgahMoADD
Mh2CGtO8rurwwDyIQ6PP/jblg6WjJOQPrD2CK8FbHqn3DPf02rAuWNBm1Ne3Ipnq
HUtRqULM
-----END PRIVATE KEY-----